#! /bin/sh

### BEGIN INIT INFO
# Provides:          blog
# Required-Start:    $all
# Required-Stop:     $all
# Short-Description: starts my blog
# Description:       starts my blog using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
COMMAND=/home/jamie/blog/start-service.sh
PROCESS=beam.smp
NAME=blog
DESC=blog
PID=/home/jamie/blog/run/blog.pid
USER=jamie

test -x $COMMAND || exit 1

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	  echo "Starting $DESC: "
	  start-stop-daemon -c $USER --start --quiet --pidfile $PID --exec $COMMAND -- $COMMAND_OPTS || true
	  echo "Done"
	  ;;
  stop)
	  echo "Stopping $DESC: "
	  start-stop-daemon --stop --quiet --pidfile $PID || true
	  echo "Done"
	  ;;
  restart)
	  echo "Restarting $DESC: "
	  start-stop-daemon --stop --quiet --pidfile $PID || true
	  sleep 1
	  start-stop-daemon -c $USER --start --quiet --pidfile $PID --exec $COMMAND -- $COMMAND_OPTS || true
	  echo "Done"
	  ;;
  status)
	  status_of_proc -p $PID "$PROCESS" blog && exit 0 || exit $?
	  ;;
  *)
	  echo "Usage: $NAME {start|stop|restart|status}" >&2
	  exit 1
	;;
esac

exit 0
